export default [
  {
    emoji: "😂",
    name: "face with tears of joy",
    shortname: ":joy:",
    unicode: "1f602",
    html: "&#128514;",
    category: "Smileys & Emotion (face-smiling)",
    order: "3",
  },
  {
    emoji: "❤️",
    name: "red heart",
    shortname: ":heart:",
    unicode: "2764",
    html: "&#10084;",
    category: "Smileys & Emotion (emotion)",
    order: "1286",
  },
  {
    emoji: "😍",
    name: "smiling face with heart-eyes",
    shortname: ":heart_eyes:",
    unicode: "1f60d",
    html: "&#128525;",
    category: "Smileys & Emotion (face-affection)",
    order: "13",
  },
  {
    emoji: "😭",
    name: "loudly crying face",
    shortname: ":sob:",
    unicode: "1f62d",
    html: "&#128557;",
    category: "Smileys & Emotion (face-concerned)",
    order: "55",
  },
  {
    emoji: "😊",
    name: "smiling face with smiling eyes",
    shortname: ":blush:",
    unicode: "1f60a",
    html: "&#128522;",
    category: "Smileys & Emotion (face-smiling)",
    order: "10",
  },
  {
    emoji: "😒",
    name: "unamused face",
    shortname: ":unamused:",
    unicode: "1f612",
    html: "&#128530;",
    category: "Smileys & Emotion (face-neutral-skeptical)",
    order: "41",
  },
  {
    emoji: "😘",
    name: "face blowing a kiss",
    shortname: ":kissing_heart:",
    unicode: "1f618",
    html: "&#128536;",
    category: "Smileys & Emotion (face-affection)",
    order: "14",
  },
  {
    emoji: "💕",
    name: "two hearts",
    shortname: ":two_hearts:",
    unicode: "1f495",
    html: "&#128149;",
    category: "Smileys & Emotion (emotion)",
    order: "1289",
  },
  {
    emoji: "😩",
    name: "weary face",
    shortname: ":weary:",
    unicode: "1f629",
    html: "&#128553;",
    category: "Smileys & Emotion (face-concerned)",
    order: "59",
  },
  {
    emoji: "👌🏿",
    name: "OK hand: dark skin tone",
    shortname: ":dark_skin_tone:",
    unicode: "1F44C 1F3FF",
    html: "&#128076;&#127999;",
    category: "People & Body (hand-fingers-partial)",
    order: "",
  },
  {
    emoji: "👌🏾",
    name: "OK hand: medium-dark skin tone",
    shortname: ":mediumdark_skin_tone:",
    unicode: "1F44C 1F3FE",
    html: "&#128076;&#127998;",
    category: "People & Body (hand-fingers-partial)",
    order: "",
  },
  {
    emoji: "👌🏽",
    name: "OK hand: medium skin tone",
    shortname: ":medium_skin_tone:",
    unicode: "1F44C 1F3FD",
    html: "&#128076;&#127997;",
    category: "People & Body (hand-fingers-partial)",
    order: "",
  },
  {
    emoji: "👌🏼",
    name: "OK hand: medium-light skin tone",
    shortname: ":mediumlight_skin_tone:",
    unicode: "1F44C 1F3FC",
    html: "&#128076;&#127996;",
    category: "People & Body (hand-fingers-partial)",
    order: "",
  },
  {
    emoji: "👌🏻",
    name: "OK hand: light skin tone",
    shortname: ":light_skin_tone:",
    unicode: "1F44C 1F3FB",
    html: "&#128076;&#127995;",
    category: "People & Body (hand-fingers-partial)",
    order: "",
  },
  {
    emoji: "👌",
    name: "OK hand",
    shortname: ":ok_hand:",
    unicode: "1f44c",
    html: "&#128076;",
    category: "People & Body (hand-fingers-partial)",
    order: "1170",
  },
  {
    emoji: "😔",
    name: "pensive face",
    shortname: ":pensive:",
    unicode: "1f614",
    html: "&#128532;",
    category: "Smileys & Emotion (face-sleepy)",
    order: "43",
  },
  {
    emoji: "😏",
    name: "smirking face",
    shortname: ":smirk:",
    unicode: "1f60f",
    html: "&#128527;",
    category: "Smileys & Emotion (face-neutral-skeptical)",
    order: "26",
  },
  {
    emoji: "😁",
    name: "beaming face with smiling eyes",
    shortname: ":grin:",
    unicode: "1f601",
    html: "&#128513;",
    category: "Smileys & Emotion (face-smiling)",
    order: "2",
  },
  {
    emoji: "😉",
    name: "winking face",
    shortname: ":wink:",
    unicode: "1f609",
    html: "&#128521;",
    category: "Smileys & Emotion (face-smiling)",
    order: "9",
  },
  {
    emoji: "👍🏿",
    name: "thumbs up: dark skin tone",
    shortname: ":dark_skin_tone:",
    unicode: "1F44D 1F3FF",
    html: "&#128077;&#127999;",
    category: "People & Body (hand-fingers-closed)",
    order: "",
  },
  {
    emoji: "👍🏾",
    name: "thumbs up: medium-dark skin tone",
    shortname: ":mediumdark_skin_tone:",
    unicode: "1F44D 1F3FE",
    html: "&#128077;&#127998;",
    category: "People & Body (hand-fingers-closed)",
    order: "",
  },
  {
    emoji: "👍🏽",
    name: "thumbs up: medium skin tone",
    shortname: ":medium_skin_tone:",
    unicode: "1F44D 1F3FD",
    html: "&#128077;&#127997;",
    category: "People & Body (hand-fingers-closed)",
    order: "",
  },
  {
    emoji: "👍🏼",
    name: "thumbs up: medium-light skin tone",
    shortname: ":mediumlight_skin_tone:",
    unicode: "1F44D 1F3FC",
    html: "&#128077;&#127996;",
    category: "People & Body (hand-fingers-closed)",
    order: "",
  },
  {
    emoji: "👍🏻",
    name: "thumbs up: light skin tone",
    shortname: ":light_skin_tone:",
    unicode: "1F44D 1F3FB",
    html: "&#128077;&#127995;",
    category: "People & Body (hand-fingers-closed)",
    order: "",
  },
  {
    emoji: "👍",
    name: "thumbs up",
    shortname: ":thumbsup:",
    unicode: "1f44d",
    html: "&#128077;",
    category: "People & Body (hand-fingers-closed)",
    order: "1176",
  },
  {
    emoji: "🙏🏿",
    name: "folded hands: dark skin tone",
    shortname: ":dark_skin_tone:",
    unicode: "1F64F 1F3FF",
    html: "&#128591;&#127999;",
    category: "People & Body (hands)",
    order: "",
  },
  {
    emoji: "🙏🏾",
    name: "folded hands: medium-dark skin tone",
    shortname: ":mediumdark_skin_tone:",
    unicode: "1F64F 1F3FE",
    html: "&#128591;&#127998;",
    category: "People & Body (hands)",
    order: "",
  },
  {
    emoji: "🙏🏽",
    name: "folded hands: medium skin tone",
    shortname: ":medium_skin_tone:",
    unicode: "1F64F 1F3FD",
    html: "&#128591;&#127997;",
    category: "People & Body (hands)",
    order: "",
  },
  {
    emoji: "🙏🏼",
    name: "folded hands: medium-light skin tone",
    shortname: ":mediumlight_skin_tone:",
    unicode: "1F64F 1F3FC",
    html: "&#128591;&#127996;",
    category: "People & Body (hands)",
    order: "",
  },
  {
    emoji: "🙏🏻",
    name: "folded hands: light skin tone",
    shortname: ":light_skin_tone:",
    unicode: "1F64F 1F3FB",
    html: "&#128591;&#127995;",
    category: "People & Body (hands)",
    order: "",
  },
  {
    emoji: "🙏",
    name: "folded hands",
    shortname: ":pray:",
    unicode: "1f64f",
    html: "&#128591;",
    category: "People & Body (hands)",
    order: "1248",
  },
  {
    emoji: "😌",
    name: "relieved face",
    shortname: ":relieved:",
    unicode: "1f60c",
    html: "&#128524;",
    category: "Smileys & Emotion (face-sleepy)",
    order: "35",
  },
  {
    emoji: "🎶",
    name: "musical notes",
    shortname: ":notes:",
    unicode: "1f3b6",
    html: "&#127926;",
    category: "Objects (music)",
    order: "1825",
  },
  {
    emoji: "😳",
    name: "flushed face",
    shortname: ":flushed:",
    unicode: "1f633",
    html: "&#128563;",
    category: "Smileys & Emotion (face-concerned)",
    order: "63",
  },
  {
    emoji: "🙌🏿",
    name: "raising hands: dark skin tone",
    shortname: ":dark_skin_tone:",
    unicode: "1F64C 1F3FF",
    html: "&#128588;&#127999;",
    category: "People & Body (hands)",
    order: "",
  },
  {
    emoji: "🙌🏾",
    name: "raising hands: medium-dark skin tone",
    shortname: ":mediumdark_skin_tone:",
    unicode: "1F64C 1F3FE",
    html: "&#128588;&#127998;",
    category: "People & Body (hands)",
    order: "",
  },
  {
    emoji: "🙌🏽",
    name: "raising hands: medium skin tone",
    shortname: ":medium_skin_tone:",
    unicode: "1F64C 1F3FD",
    html: "&#128588;&#127997;",
    category: "People & Body (hands)",
    order: "",
  },
  {
    emoji: "🙌🏼",
    name: "raising hands: medium-light skin tone",
    shortname: ":mediumlight_skin_tone:",
    unicode: "1F64C 1F3FC",
    html: "&#128588;&#127996;",
    category: "People & Body (hands)",
    order: "",
  },
  {
    emoji: "🙌🏻",
    name: "raising hands: light skin tone",
    shortname: ":light_skin_tone:",
    unicode: "1F64C 1F3FB",
    html: "&#128588;&#127995;",
    category: "People & Body (hands)",
    order: "",
  },
  {
    emoji: "🙌",
    name: "raising hands",
    shortname: ":raised_hands:",
    unicode: "1f64c",
    html: "&#128588;",
    category: "People & Body (hands)",
    order: "1242",
  },
  {
    emoji: "🙈",
    name: "see-no-evil monkey",
    shortname: ":see_no_evil:",
    unicode: "1f648",
    html: "&#128584;",
    category: "Smileys & Emotion (monkey-face)",
    order: "96",
  },
  {
    emoji: "😢",
    name: "crying face",
    shortname: ":cry:",
    unicode: "1f622",
    html: "&#128546;",
    category: "Smileys & Emotion (face-concerned)",
    order: "54",
  },
  {
    emoji: "😎",
    name: "smiling face with sunglasses",
    shortname: ":sunglasses:",
    unicode: "1f60e",
    html: "&#128526;",
    category: "Smileys & Emotion (face-glasses)",
    order: "12",
  },
  {
    emoji: "✌🏿",
    name: "victory hand: dark skin tone",
    shortname: ":dark_skin_tone:",
    unicode: "270C 1F3FF",
    html: "&#9996;&#127999;",
    category: "People & Body (hand-fingers-partial)",
    order: "",
  },
  {
    emoji: "✌🏾",
    name: "victory hand: medium-dark skin tone",
    shortname: ":mediumdark_skin_tone:",
    unicode: "270C 1F3FE",
    html: "&#9996;&#127998;",
    category: "People & Body (hand-fingers-partial)",
    order: "",
  },
  {
    emoji: "✌🏽",
    name: "victory hand: medium skin tone",
    shortname: ":medium_skin_tone:",
    unicode: "270C 1F3FD",
    html: "&#9996;&#127997;",
    category: "People & Body (hand-fingers-partial)",
    order: "",
  },
  {
    emoji: "✌🏼",
    name: "victory hand: medium-light skin tone",
    shortname: ":mediumlight_skin_tone:",
    unicode: "270C 1F3FC",
    html: "&#9996;&#127996;",
    category: "People & Body (hand-fingers-partial)",
    order: "",
  },
  {
    emoji: "✌🏻",
    name: "victory hand: light skin tone",
    shortname: ":light_skin_tone:",
    unicode: "270C 1F3FB",
    html: "&#9996;&#127995;",
    category: "People & Body (hand-fingers-partial)",
    order: "",
  },
  {
    emoji: "✌️",
    name: "victory hand",
    shortname: ":v:",
    unicode: "270c",
    html: "&#9996;",
    category: "People & Body (hand-fingers-partial)",
    order: "1128",
  },
  {
    emoji: "👀",
    name: "eyes",
    shortname: ":eyes:",
    unicode: "1f440",
    html: "&#128064;",
    category: "People & Body (body-parts)",
    order: "1279",
  },
  {
    emoji: "😅",
    name: "grinning face with sweat",
    shortname: ":sweat_smile:",
    unicode: "1f605",
    html: "&#128517;",
    category: "Smileys & Emotion (face-smiling)",
    order: "7",
  },
  {
    emoji: "✨",
    name: "sparkles",
    shortname: ":sparkles:",
    unicode: "2728",
    html: "&#10024;",
    category: "Activities (event)",
    order: "1760",
  },
  {
    emoji: "😴",
    name: "sleeping face",
    shortname: ":sleeping:",
    unicode: "1f634",
    html: "&#128564;",
    category: "Smileys & Emotion (face-sleepy)",
    order: "34",
  },
  {
    emoji: "😄",
    name: "grinning face with smiling eyes",
    shortname: ":smile:",
    unicode: "1f604",
    html: "&#128516;",
    category: "Smileys & Emotion (face-smiling)",
    order: "6",
  },
  {
    emoji: "💜",
    name: "purple heart",
    shortname: ":purple_heart:",
    unicode: "1f49c",
    html: "&#128156;",
    category: "Smileys & Emotion (emotion)",
    order: "1295",
  },
  {
    emoji: "💔",
    name: "broken heart",
    shortname: ":broken_heart:",
    unicode: "1f494",
    html: "&#128148;",
    category: "Smileys & Emotion (emotion)",
    order: "1288",
  },
  {
    emoji: "💯",
    name: "hundred points",
    shortname: ":hundred_points:",
    unicode: "1F4AF",
    html: "&#128175;",
    category: "Smileys & Emotion (emotion)",
    order: "",
  },
  {
    emoji: "😑",
    name: "expressionless face",
    shortname: ":expressionless:",
    unicode: "1f611",
    html: "&#128529;",
    category: "Smileys & Emotion (face-neutral-skeptical)",
    order: "23",
  },
  {
    emoji: "💖",
    name: "sparkling heart",
    shortname: ":sparkling_heart:",
    unicode: "1f496",
    html: "&#128150;",
    category: "Smileys & Emotion (emotion)",
    order: "1290",
  },
  {
    emoji: "💙",
    name: "blue heart",
    shortname: ":blue_heart:",
    unicode: "1f499",
    html: "&#128153;",
    category: "Smileys & Emotion (emotion)",
    order: "1292",
  },
  {
    emoji: "😕",
    name: "confused face",
    shortname: ":confused:",
    unicode: "1f615",
    html: "&#128533;",
    category: "Smileys & Emotion (face-concerned)",
    order: "44",
  },
  {
    emoji: "💁🏿‍♂",
    name: "man tipping hand: dark skin tone",
    shortname: ":dark_skin_tone:",
    unicode: "1F481 1F3FF 200D 2642",
    html: "&#128129;&#127999;&zwj;&#9794;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "💁🏾‍♂",
    name: "man tipping hand: medium-dark skin tone",
    shortname: ":mediumdark_skin_tone:",
    unicode: "1F481 1F3FE 200D 2642",
    html: "&#128129;&#127998;&zwj;&#9794;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "💁🏽‍♂",
    name: "man tipping hand: medium skin tone",
    shortname: ":medium_skin_tone:",
    unicode: "1F481 1F3FD 200D 2642",
    html: "&#128129;&#127997;&zwj;&#9794;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "💁🏼‍♂",
    name: "man tipping hand: medium-light skin tone",
    shortname: ":mediumlight_skin_tone:",
    unicode: "1F481 1F3FC 200D 2642",
    html: "&#128129;&#127996;&zwj;&#9794;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "💁🏻‍♂",
    name: "man tipping hand: light skin tone",
    shortname: ":light_skin_tone:",
    unicode: "1F481 1F3FB 200D 2642",
    html: "&#128129;&#127995;&zwj;&#9794;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "💁‍♂",
    name: "man tipping hand",
    shortname: ":man_tipping_hand:",
    unicode: "1F481 200D 2642",
    html: "&#128129;&zwj;&#9794;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "💁🏿",
    name: "person tipping hand: dark skin tone",
    shortname: ":dark_skin_tone:",
    unicode: "1F481 1F3FF",
    html: "&#128129;&#127999;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "💁🏾",
    name: "person tipping hand: medium-dark skin tone",
    shortname: ":mediumdark_skin_tone:",
    unicode: "1F481 1F3FE",
    html: "&#128129;&#127998;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "💁🏽",
    name: "person tipping hand: medium skin tone",
    shortname: ":medium_skin_tone:",
    unicode: "1F481 1F3FD",
    html: "&#128129;&#127997;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "💁🏼",
    name: "person tipping hand: medium-light skin tone",
    shortname: ":mediumlight_skin_tone:",
    unicode: "1F481 1F3FC",
    html: "&#128129;&#127996;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "💁🏻",
    name: "person tipping hand: light skin tone",
    shortname: ":light_skin_tone:",
    unicode: "1F481 1F3FB",
    html: "&#128129;&#127995;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "💁",
    name: "person tipping hand",
    shortname: ":information_desk_person:",
    unicode: "1f481",
    html: "&#128129;",
    category: "People & Body (person-gesture)",
    order: "567",
  },
  {
    emoji: "😜",
    name: "winking face with tongue",
    shortname: ":stuck_out_tongue_winking_eye:",
    unicode: "1f61c",
    html: "&#128540;",
    category: "Smileys & Emotion (face-tongue)",
    order: "38",
  },
  {
    emoji: "😞",
    name: "disappointed face",
    shortname: ":disappointed:",
    unicode: "1f61e",
    html: "&#128542;",
    category: "Smileys & Emotion (face-concerned)",
    order: "51",
  },
  {
    emoji: "😋",
    name: "face savoring food",
    shortname: ":yum:",
    unicode: "1f60b",
    html: "&#128523;",
    category: "Smileys & Emotion (face-tongue)",
    order: "11",
  },
  {
    emoji: "😐",
    name: "neutral face",
    shortname: ":neutral_face:",
    unicode: "1f610",
    html: "&#128528;",
    category: "Smileys & Emotion (face-neutral-skeptical)",
    order: "22",
  },
  {
    emoji: "😪",
    name: "sleepy face",
    shortname: ":sleepy:",
    unicode: "1f62a",
    html: "&#128554;",
    category: "Smileys & Emotion (face-sleepy)",
    order: "32",
  },
  {
    emoji: "👏🏿",
    name: "clapping hands: dark skin tone",
    shortname: ":dark_skin_tone:",
    unicode: "1F44F 1F3FF",
    html: "&#128079;&#127999;",
    category: "People & Body (hands)",
    order: "",
  },
  {
    emoji: "👏🏾",
    name: "clapping hands: medium-dark skin tone",
    shortname: ":mediumdark_skin_tone:",
    unicode: "1F44F 1F3FE",
    html: "&#128079;&#127998;",
    category: "People & Body (hands)",
    order: "",
  },
  {
    emoji: "👏🏽",
    name: "clapping hands: medium skin tone",
    shortname: ":medium_skin_tone:",
    unicode: "1F44F 1F3FD",
    html: "&#128079;&#127997;",
    category: "People & Body (hands)",
    order: "",
  },
  {
    emoji: "👏🏼",
    name: "clapping hands: medium-light skin tone",
    shortname: ":mediumlight_skin_tone:",
    unicode: "1F44F 1F3FC",
    html: "&#128079;&#127996;",
    category: "People & Body (hands)",
    order: "",
  },
  {
    emoji: "👏🏻",
    name: "clapping hands: light skin tone",
    shortname: ":light_skin_tone:",
    unicode: "1F44F 1F3FB",
    html: "&#128079;&#127995;",
    category: "People & Body (hands)",
    order: "",
  },
  {
    emoji: "👏",
    name: "clapping hands",
    shortname: ":clap:",
    unicode: "1f44f",
    html: "&#128079;",
    category: "People & Body (hands)",
    order: "1224",
  },
  {
    emoji: "💘",
    name: "heart with arrow",
    shortname: ":cupid:",
    unicode: "1f498",
    html: "&#128152;",
    category: "Smileys & Emotion (emotion)",
    order: "1285",
  },
  {
    emoji: "💗",
    name: "growing heart",
    shortname: ":heartpulse:",
    unicode: "1f497",
    html: "&#128151;",
    category: "Smileys & Emotion (emotion)",
    order: "1291",
  },
  {
    emoji: "💞",
    name: "revolving hearts",
    shortname: ":revolving_hearts:",
    unicode: "1f49e",
    html: "&#128158;",
    category: "Smileys & Emotion (emotion)",
    order: "1298",
  },
  {
    emoji: "⬅️",
    name: "left arrow",
    shortname: ":arrow_left:",
    unicode: "2b05",
    html: "&#11013;",
    category: "Symbols (arrow)",
    order: "2008",
  },
  {
    emoji: "🙊",
    name: "speak-no-evil monkey",
    shortname: ":speak_no_evil:",
    unicode: "1f64a",
    html: "&#128586;",
    category: "Smileys & Emotion (monkey-face)",
    order: "98",
  },
  {
    emoji: "✋🏿",
    name: "raised hand: dark skin tone",
    shortname: ":dark_skin_tone:",
    unicode: "270B 1F3FF",
    html: "&#9995;&#127999;",
    category: "People & Body (hand-fingers-open)",
    order: "",
  },
  {
    emoji: "✋🏾",
    name: "raised hand: medium-dark skin tone",
    shortname: ":mediumdark_skin_tone:",
    unicode: "270B 1F3FE",
    html: "&#9995;&#127998;",
    category: "People & Body (hand-fingers-open)",
    order: "",
  },
  {
    emoji: "✋🏽",
    name: "raised hand: medium skin tone",
    shortname: ":medium_skin_tone:",
    unicode: "270B 1F3FD",
    html: "&#9995;&#127997;",
    category: "People & Body (hand-fingers-open)",
    order: "",
  },
  {
    emoji: "✋🏼",
    name: "raised hand: medium-light skin tone",
    shortname: ":mediumlight_skin_tone:",
    unicode: "270B 1F3FC",
    html: "&#9995;&#127996;",
    category: "People & Body (hand-fingers-open)",
    order: "",
  },
  {
    emoji: "✋🏻",
    name: "raised hand: light skin tone",
    shortname: ":light_skin_tone:",
    unicode: "270B 1F3FB",
    html: "&#9995;&#127995;",
    category: "People & Body (hand-fingers-open)",
    order: "",
  },
  {
    emoji: "✋",
    name: "raised hand",
    shortname: ":raised_hand:",
    unicode: "270B",
    html: "&#9995;",
    category: "People & Body (hand-fingers-open)",
    order: "",
  },
  {
    emoji: "💋",
    name: "kiss mark",
    shortname: ":kiss:",
    unicode: "1f48b",
    html: "&#128139;",
    category: "Smileys & Emotion (emotion)",
    order: "1284",
  },
  {
    emoji: "👉🏿",
    name: "backhand index pointing right: dark skin tone",
    shortname: ":dark_skin_tone:",
    unicode: "1F449 1F3FF",
    html: "&#128073;&#127999;",
    category: "People & Body (hand-single-finger)",
    order: "",
  },
  {
    emoji: "👉🏾",
    name: "backhand index pointing right: medium-dark skin tone",
    shortname: ":mediumdark_skin_tone:",
    unicode: "1F449 1F3FE",
    html: "&#128073;&#127998;",
    category: "People & Body (hand-single-finger)",
    order: "",
  },
  {
    emoji: "👉🏽",
    name: "backhand index pointing right: medium skin tone",
    shortname: ":medium_skin_tone:",
    unicode: "1F449 1F3FD",
    html: "&#128073;&#127997;",
    category: "People & Body (hand-single-finger)",
    order: "",
  },
  {
    emoji: "👉🏼",
    name: "backhand index pointing right: medium-light skin tone",
    shortname: ":mediumlight_skin_tone:",
    unicode: "1F449 1F3FC",
    html: "&#128073;&#127996;",
    category: "People & Body (hand-single-finger)",
    order: "",
  },
  {
    emoji: "👉🏻",
    name: "backhand index pointing right: light skin tone",
    shortname: ":light_skin_tone:",
    unicode: "1F449 1F3FB",
    html: "&#128073;&#127995;",
    category: "People & Body (hand-single-finger)",
    order: "",
  },
  {
    emoji: "👉",
    name: "backhand index pointing right",
    shortname: ":point_right:",
    unicode: "1f449",
    html: "&#128073;",
    category: "People & Body (hand-single-finger)",
    order: "1098",
  },
  {
    emoji: "🌸",
    name: "cherry blossom",
    shortname: ":cherry_blossom:",
    unicode: "1f338",
    html: "&#127800;",
    category: "Animals & Nature (plant-flower)",
    order: "1428",
  },
  {
    emoji: "😱",
    name: "face screaming in fear",
    shortname: ":scream:",
    unicode: "1f631",
    html: "&#128561;",
    category: "Smileys & Emotion (face-concerned)",
    order: "62",
  },
  {
    emoji: "🔥",
    name: "fire",
    shortname: ":fire:",
    unicode: "1f525",
    html: "&#128293;",
    category: "Travel & Places (sky & weather)",
    order: "1753",
  },
  {
    emoji: "😡",
    name: "pouting face",
    shortname: ":rage:",
    unicode: "1f621",
    html: "&#128545;",
    category: "Smileys & Emotion (face-negative)",
    order: "65",
  },
  {
    emoji: "😃",
    name: "grinning face with big eyes",
    shortname: ":smiley:",
    unicode: "1f603",
    html: "&#128515;",
    category: "Smileys & Emotion (face-smiling)",
    order: "5",
  },
  {
    emoji: "🎉",
    name: "party popper",
    shortname: ":tada:",
    unicode: "1f389",
    html: "&#127881;",
    category: "Activities (event)",
    order: "1762",
  },
  {
    emoji: "👊🏿",
    name: "oncoming fist: dark skin tone",
    shortname: ":dark_skin_tone:",
    unicode: "1F44A 1F3FF",
    html: "&#128074;&#127999;",
    category: "People & Body (hand-fingers-closed)",
    order: "",
  },
  {
    emoji: "👊🏾",
    name: "oncoming fist: medium-dark skin tone",
    shortname: ":mediumdark_skin_tone:",
    unicode: "1F44A 1F3FE",
    html: "&#128074;&#127998;",
    category: "People & Body (hand-fingers-closed)",
    order: "",
  },
  {
    emoji: "👊🏽",
    name: "oncoming fist: medium skin tone",
    shortname: ":medium_skin_tone:",
    unicode: "1F44A 1F3FD",
    html: "&#128074;&#127997;",
    category: "People & Body (hand-fingers-closed)",
    order: "",
  },
  {
    emoji: "👊🏼",
    name: "oncoming fist: medium-light skin tone",
    shortname: ":mediumlight_skin_tone:",
    unicode: "1F44A 1F3FC",
    html: "&#128074;&#127996;",
    category: "People & Body (hand-fingers-closed)",
    order: "",
  },
  {
    emoji: "👊🏻",
    name: "oncoming fist: light skin tone",
    shortname: ":light_skin_tone:",
    unicode: "1F44A 1F3FB",
    html: "&#128074;&#127995;",
    category: "People & Body (hand-fingers-closed)",
    order: "",
  },
  {
    emoji: "👊",
    name: "oncoming fist",
    shortname: ":oncoming_fist:",
    unicode: "1F44A",
    html: "&#128074;",
    category: "People & Body (hand-fingers-closed)",
    order: "",
  },
  {
    emoji: "😫",
    name: "tired face",
    shortname: ":tired_face:",
    unicode: "1f62b",
    html: "&#128555;",
    category: "Smileys & Emotion (face-concerned)",
    order: "33",
  },
  {
    emoji: "📷",
    name: "camera",
    shortname: ":camera:",
    unicode: "1f4f7",
    html: "&#128247;",
    category: "Objects (light & video)",
    order: "1861",
  },
  {
    emoji: "🌹",
    name: "rose",
    shortname: ":rose:",
    unicode: "1f339",
    html: "&#127801;",
    category: "Animals & Nature (plant-flower)",
    order: "1431",
  },
  {
    emoji: "😝",
    name: "squinting face with tongue",
    shortname: ":stuck_out_tongue_closed_eyes:",
    unicode: "1f61d",
    html: "&#128541;",
    category: "Smileys & Emotion (face-tongue)",
    order: "39",
  },
  {
    emoji: "💪🏿",
    name: "flexed biceps: dark skin tone",
    shortname: ":dark_skin_tone:",
    unicode: "1F4AA 1F3FF",
    html: "&#128170;&#127999;",
    category: "People & Body (body-parts)",
    order: "",
  },
  {
    emoji: "💪🏾",
    name: "flexed biceps: medium-dark skin tone",
    shortname: ":mediumdark_skin_tone:",
    unicode: "1F4AA 1F3FE",
    html: "&#128170;&#127998;",
    category: "People & Body (body-parts)",
    order: "",
  },
  {
    emoji: "💪🏽",
    name: "flexed biceps: medium skin tone",
    shortname: ":medium_skin_tone:",
    unicode: "1F4AA 1F3FD",
    html: "&#128170;&#127997;",
    category: "People & Body (body-parts)",
    order: "",
  },
  {
    emoji: "💪🏼",
    name: "flexed biceps: medium-light skin tone",
    shortname: ":mediumlight_skin_tone:",
    unicode: "1F4AA 1F3FC",
    html: "&#128170;&#127996;",
    category: "People & Body (body-parts)",
    order: "",
  },
  {
    emoji: "💪🏻",
    name: "flexed biceps: light skin tone",
    shortname: ":light_skin_tone:",
    unicode: "1F4AA 1F3FB",
    html: "&#128170;&#127995;",
    category: "People & Body (body-parts)",
    order: "",
  },
  {
    emoji: "💪",
    name: "flexed biceps",
    shortname: ":muscle:",
    unicode: "1f4aa",
    html: "&#128170;",
    category: "People & Body (body-parts)",
    order: "1080",
  },
  {
    emoji: "💀",
    name: "skull",
    shortname: ":skull:",
    unicode: "1f480",
    html: "&#128128;",
    category: "Smileys & Emotion (face-negative)",
    order: "80",
  },
  {
    emoji: "☀️",
    name: "sun",
    shortname: ":sunny:",
    unicode: "2600",
    html: "&#9728;",
    category: "Travel & Places (sky & weather)",
    order: "1724",
  },
  {
    emoji: "💛",
    name: "yellow heart",
    shortname: ":yellow_heart:",
    unicode: "1f49b",
    html: "&#128155;",
    category: "Smileys & Emotion (emotion)",
    order: "1294",
  },
  {
    emoji: "😤",
    name: "face with steam from nose",
    shortname: ":triumph:",
    unicode: "1f624",
    html: "&#128548;",
    category: "Smileys & Emotion (face-negative)",
    order: "53",
  },
  {
    emoji: "🌚",
    name: "new moon face",
    shortname: ":new_moon_with_face:",
    unicode: "1f31a",
    html: "&#127770;",
    category: "Travel & Places (sky & weather)",
    order: "1720",
  },
  {
    emoji: "😆",
    name: "grinning squinting face",
    shortname: ":laughing:",
    unicode: "1f606",
    html: "&#128518;",
    category: "Smileys & Emotion (face-smiling)",
    order: "8",
  },
  {
    emoji: "😓",
    name: "downcast face with sweat",
    shortname: ":sweat:",
    unicode: "1f613",
    html: "&#128531;",
    category: "Smileys & Emotion (face-concerned)",
    order: "42",
  },
  {
    emoji: "👈🏿",
    name: "backhand index pointing left: dark skin tone",
    shortname: ":dark_skin_tone:",
    unicode: "1F448 1F3FF",
    html: "&#128072;&#127999;",
    category: "People & Body (hand-single-finger)",
    order: "",
  },
  {
    emoji: "👈🏾",
    name: "backhand index pointing left: medium-dark skin tone",
    shortname: ":mediumdark_skin_tone:",
    unicode: "1F448 1F3FE",
    html: "&#128072;&#127998;",
    category: "People & Body (hand-single-finger)",
    order: "",
  },
  {
    emoji: "👈🏽",
    name: "backhand index pointing left: medium skin tone",
    shortname: ":medium_skin_tone:",
    unicode: "1F448 1F3FD",
    html: "&#128072;&#127997;",
    category: "People & Body (hand-single-finger)",
    order: "",
  },
  {
    emoji: "👈🏼",
    name: "backhand index pointing left: medium-light skin tone",
    shortname: ":mediumlight_skin_tone:",
    unicode: "1F448 1F3FC",
    html: "&#128072;&#127996;",
    category: "People & Body (hand-single-finger)",
    order: "",
  },
  {
    emoji: "👈🏻",
    name: "backhand index pointing left: light skin tone",
    shortname: ":light_skin_tone:",
    unicode: "1F448 1F3FB",
    html: "&#128072;&#127995;",
    category: "People & Body (hand-single-finger)",
    order: "",
  },
  {
    emoji: "👈",
    name: "backhand index pointing left",
    shortname: ":point_left:",
    unicode: "1f448",
    html: "&#128072;",
    category: "People & Body (hand-single-finger)",
    order: "1092",
  },
  {
    emoji: "✔️",
    name: "check mark",
    shortname: ":heavy_check_mark:",
    unicode: "2714",
    html: "&#10004;",
    category: "Symbols (other-symbol)",
    order: "2080",
  },
  {
    emoji: "😻",
    name: "smiling cat with heart-eyes",
    shortname: ":heart_eyes_cat:",
    unicode: "1f63b",
    html: "&#128571;",
    category: "Smileys & Emotion (cat-face)",
    order: "90",
  },
  {
    emoji: "😀",
    name: "grinning face",
    shortname: ":grinning:",
    unicode: "1f600",
    html: "&#128512;",
    category: "Smileys & Emotion (face-smiling)",
    order: "1",
  },
  {
    emoji: "😷",
    name: "face with medical mask",
    shortname: ":mask:",
    unicode: "1f637",
    html: "&#128567;",
    category: "Smileys & Emotion (face-unwell)",
    order: "71",
  },
  {
    emoji: "💚",
    name: "green heart",
    shortname: ":green_heart:",
    unicode: "1f49a",
    html: "&#128154;",
    category: "Smileys & Emotion (emotion)",
    order: "1293",
  },
  {
    emoji: "👋🏿",
    name: "waving hand: dark skin tone",
    shortname: ":dark_skin_tone:",
    unicode: "1F44B 1F3FF",
    html: "&#128075;&#127999;",
    category: "People & Body (hand-fingers-open)",
    order: "",
  },
  {
    emoji: "👋🏾",
    name: "waving hand: medium-dark skin tone",
    shortname: ":mediumdark_skin_tone:",
    unicode: "1F44B 1F3FE",
    html: "&#128075;&#127998;",
    category: "People & Body (hand-fingers-open)",
    order: "",
  },
  {
    emoji: "👋🏽",
    name: "waving hand: medium skin tone",
    shortname: ":medium_skin_tone:",
    unicode: "1F44B 1F3FD",
    html: "&#128075;&#127997;",
    category: "People & Body (hand-fingers-open)",
    order: "",
  },
  {
    emoji: "👋🏼",
    name: "waving hand: medium-light skin tone",
    shortname: ":mediumlight_skin_tone:",
    unicode: "1F44B 1F3FC",
    html: "&#128075;&#127996;",
    category: "People & Body (hand-fingers-open)",
    order: "",
  },
  {
    emoji: "👋🏻",
    name: "waving hand: light skin tone",
    shortname: ":light_skin_tone:",
    unicode: "1F44B 1F3FB",
    html: "&#128075;&#127995;",
    category: "People & Body (hand-fingers-open)",
    order: "",
  },
  {
    emoji: "👋",
    name: "waving hand",
    shortname: ":wave:",
    unicode: "1f44b",
    html: "&#128075;",
    category: "People & Body (hand-fingers-open)",
    order: "1218",
  },
  {
    emoji: "😣",
    name: "persevering face",
    shortname: ":persevere:",
    unicode: "1f623",
    html: "&#128547;",
    category: "Smileys & Emotion (face-concerned)",
    order: "27",
  },
  {
    emoji: "💓",
    name: "beating heart",
    shortname: ":heartbeat:",
    unicode: "1f493",
    html: "&#128147;",
    category: "Smileys & Emotion (emotion)",
    order: "1287",
  },
  {
    emoji: "▶️",
    name: "play button",
    shortname: ":arrow_forward:",
    unicode: "25b6",
    html: "&#9654;",
    category: "Symbols (av-symbol)",
    order: "2051",
  },
  {
    emoji: "◀️",
    name: "reverse button",
    shortname: ":arrow_backward:",
    unicode: "25c0",
    html: "&#9664;",
    category: "Symbols (av-symbol)",
    order: "2055",
  },
  {
    emoji: "↪️",
    name: "left arrow curving right",
    shortname: ":arrow_right_hook:",
    unicode: "21aa",
    html: "&#8618;",
    category: "Symbols (arrow)",
    order: "2013",
  },
  {
    emoji: "↩️",
    name: "right arrow curving left",
    shortname: ":leftwards_arrow_with_hook:",
    unicode: "21a9",
    html: "&#8617;",
    category: "Symbols (arrow)",
    order: "2012",
  },
  {
    emoji: "👑",
    name: "crown",
    shortname: ":crown:",
    unicode: "1f451",
    html: "&#128081;",
    category: "Objects (clothing)",
    order: "1333",
  },
  {
    emoji: "😚",
    name: "kissing face with closed eyes",
    shortname: ":kissing_closed_eyes:",
    unicode: "1f61a",
    html: "&#128538;",
    category: "Smileys & Emotion (face-affection)",
    order: "17",
  },
  {
    emoji: "😛",
    name: "face with tongue",
    shortname: ":stuck_out_tongue:",
    unicode: "1f61b",
    html: "&#128539;",
    category: "Smileys & Emotion (face-tongue)",
    order: "37",
  },
  {
    emoji: "😥",
    name: "sad but relieved face",
    shortname: ":disappointed_relieved:",
    unicode: "1f625",
    html: "&#128549;",
    category: "Smileys & Emotion (face-concerned)",
    order: "28",
  },
  {
    emoji: "😇",
    name: "smiling face with halo",
    shortname: ":innocent:",
    unicode: "1f607",
    html: "&#128519;",
    category: "Smileys & Emotion (face-smiling)",
    order: "67",
  },
  {
    emoji: "🎧",
    name: "headphone",
    shortname: ":headphones:",
    unicode: "1f3a7",
    html: "&#127911;",
    category: "Objects (music)",
    order: "1830",
  },
  {
    emoji: "✅",
    name: "check mark button",
    shortname: ":white_check_mark:",
    unicode: "2705",
    html: "&#9989;",
    category: "Symbols (other-symbol)",
    order: "2078",
  },
  {
    emoji: "😖",
    name: "confounded face",
    shortname: ":confounded:",
    unicode: "1f616",
    html: "&#128534;",
    category: "Smileys & Emotion (face-concerned)",
    order: "50",
  },
  {
    emoji: "➡",
    name: "right arrow",
    shortname: ":arrow_right:",
    unicode: "27a1",
    html: "&#10145;",
    category: "Symbols (arrow)",
    order: "2004",
  },
  {
    emoji: "😠",
    name: "angry face",
    shortname: ":angry:",
    unicode: "1f620",
    html: "&#128544;",
    category: "Smileys & Emotion (face-negative)",
    order: "66",
  },
  {
    emoji: "😬",
    name: "grimacing face",
    shortname: ":grimacing:",
    unicode: "1f62c",
    html: "&#128556;",
    category: "Smileys & Emotion (face-neutral-skeptical)",
    order: "60",
  },
  {
    emoji: "🌟",
    name: "glowing star",
    shortname: ":star2:",
    unicode: "1f31f",
    html: "&#127775;",
    category: "Travel & Places (sky & weather)",
    order: "1728",
  },
  {
    emoji: "🔫",
    name: "pistol",
    shortname: ":gun:",
    unicode: "1f52b",
    html: "&#128299;",
    category: "Objects (tool)",
    order: "1956",
  },
  {
    emoji: "🙋🏿‍♂",
    name: "man raising hand: dark skin tone",
    shortname: ":dark_skin_tone:",
    unicode: "1F64B 1F3FF 200D 2642",
    html: "&#128587;&#127999;&zwj;&#9794;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙋🏾‍♂",
    name: "man raising hand: medium-dark skin tone",
    shortname: ":mediumdark_skin_tone:",
    unicode: "1F64B 1F3FE 200D 2642",
    html: "&#128587;&#127998;&zwj;&#9794;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙋🏽‍♂",
    name: "man raising hand: medium skin tone",
    shortname: ":medium_skin_tone:",
    unicode: "1F64B 1F3FD 200D 2642",
    html: "&#128587;&#127997;&zwj;&#9794;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙋🏼‍♂",
    name: "man raising hand: medium-light skin tone",
    shortname: ":mediumlight_skin_tone:",
    unicode: "1F64B 1F3FC 200D 2642",
    html: "&#128587;&#127996;&zwj;&#9794;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙋🏻‍♂",
    name: "man raising hand: light skin tone",
    shortname: ":light_skin_tone:",
    unicode: "1F64B 1F3FB 200D 2642",
    html: "&#128587;&#127995;&zwj;&#9794;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙋‍♂",
    name: "man raising hand",
    shortname: ":man_raising_hand:",
    unicode: "1F64B 200D 2642",
    html: "&#128587;&zwj;&#9794;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙋🏿",
    name: "person raising hand: dark skin tone",
    shortname: ":dark_skin_tone:",
    unicode: "1F64B 1F3FF",
    html: "&#128587;&#127999;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙋🏾",
    name: "person raising hand: medium-dark skin tone",
    shortname: ":mediumdark_skin_tone:",
    unicode: "1F64B 1F3FE",
    html: "&#128587;&#127998;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙋🏽",
    name: "person raising hand: medium skin tone",
    shortname: ":medium_skin_tone:",
    unicode: "1F64B 1F3FD",
    html: "&#128587;&#127997;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙋🏼",
    name: "person raising hand: medium-light skin tone",
    shortname: ":mediumlight_skin_tone:",
    unicode: "1F64B 1F3FC",
    html: "&#128587;&#127996;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙋🏻",
    name: "person raising hand: light skin tone",
    shortname: ":light_skin_tone:",
    unicode: "1F64B 1F3FB",
    html: "&#128587;&#127995;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙋",
    name: "person raising hand",
    shortname: ":raising_hand:",
    unicode: "1f64b",
    html: "&#128587;",
    category: "People & Body (person-gesture)",
    order: "585",
  },
  {
    emoji: "👎🏿",
    name: "thumbs down: dark skin tone",
    shortname: ":dark_skin_tone:",
    unicode: "1F44E 1F3FF",
    html: "&#128078;&#127999;",
    category: "People & Body (hand-fingers-closed)",
    order: "",
  },
  {
    emoji: "👎🏾",
    name: "thumbs down: medium-dark skin tone",
    shortname: ":mediumdark_skin_tone:",
    unicode: "1F44E 1F3FE",
    html: "&#128078;&#127998;",
    category: "People & Body (hand-fingers-closed)",
    order: "",
  },
  {
    emoji: "👎🏽",
    name: "thumbs down: medium skin tone",
    shortname: ":medium_skin_tone:",
    unicode: "1F44E 1F3FD",
    html: "&#128078;&#127997;",
    category: "People & Body (hand-fingers-closed)",
    order: "",
  },
  {
    emoji: "👎🏼",
    name: "thumbs down: medium-light skin tone",
    shortname: ":mediumlight_skin_tone:",
    unicode: "1F44E 1F3FC",
    html: "&#128078;&#127996;",
    category: "People & Body (hand-fingers-closed)",
    order: "",
  },
  {
    emoji: "👎🏻",
    name: "thumbs down: light skin tone",
    shortname: ":light_skin_tone:",
    unicode: "1F44E 1F3FB",
    html: "&#128078;&#127995;",
    category: "People & Body (hand-fingers-closed)",
    order: "",
  },
  {
    emoji: "👎",
    name: "thumbs down",
    shortname: ":thumbsdown:",
    unicode: "1f44e",
    html: "&#128078;",
    category: "People & Body (hand-fingers-closed)",
    order: "1182",
  },
  {
    emoji: "💃🏿",
    name: "woman dancing: dark skin tone",
    shortname: ":dark_skin_tone:",
    unicode: "1F483 1F3FF",
    html: "&#128131;&#127999;",
    category: "People & Body (person-activity)",
    order: "",
  },
  {
    emoji: "💃🏾",
    name: "woman dancing: medium-dark skin tone",
    shortname: ":mediumdark_skin_tone:",
    unicode: "1F483 1F3FE",
    html: "&#128131;&#127998;",
    category: "People & Body (person-activity)",
    order: "",
  },
  {
    emoji: "💃🏽",
    name: "woman dancing: medium skin tone",
    shortname: ":medium_skin_tone:",
    unicode: "1F483 1F3FD",
    html: "&#128131;&#127997;",
    category: "People & Body (person-activity)",
    order: "",
  },
  {
    emoji: "💃🏼",
    name: "woman dancing: medium-light skin tone",
    shortname: ":mediumlight_skin_tone:",
    unicode: "1F483 1F3FC",
    html: "&#128131;&#127996;",
    category: "People & Body (person-activity)",
    order: "",
  },
  {
    emoji: "💃🏻",
    name: "woman dancing: light skin tone",
    shortname: ":light_skin_tone:",
    unicode: "1F483 1F3FB",
    html: "&#128131;&#127995;",
    category: "People & Body (person-activity)",
    order: "",
  },
  {
    emoji: "💃",
    name: "woman dancing",
    shortname: ":dancer:",
    unicode: "1f483",
    html: "&#128131;",
    category: "People & Body (person-activity)",
    order: "729",
  },
  {
    emoji: "🎵",
    name: "musical note",
    shortname: ":musical_note:",
    unicode: "1f3b5",
    html: "&#127925;",
    category: "Objects (music)",
    order: "1824",
  },
  {
    emoji: "😶",
    name: "face without mouth",
    shortname: ":no_mouth:",
    unicode: "1f636",
    html: "&#128566;",
    category: "Smileys & Emotion (face-neutral-skeptical)",
    order: "24",
  },
  {
    emoji: "💫",
    name: "dizzy",
    shortname: ":dizzy:",
    unicode: "1f4ab",
    html: "&#128171;",
    category: "Smileys & Emotion (emotion)",
    order: "1308",
  },
  {
    emoji: "✊🏿",
    name: "raised fist: dark skin tone",
    shortname: ":dark_skin_tone:",
    unicode: "270A 1F3FF",
    html: "&#9994;&#127999;",
    category: "People & Body (hand-fingers-closed)",
    order: "",
  },
  {
    emoji: "✊🏾",
    name: "raised fist: medium-dark skin tone",
    shortname: ":mediumdark_skin_tone:",
    unicode: "270A 1F3FE",
    html: "&#9994;&#127998;",
    category: "People & Body (hand-fingers-closed)",
    order: "",
  },
  {
    emoji: "✊🏽",
    name: "raised fist: medium skin tone",
    shortname: ":medium_skin_tone:",
    unicode: "270A 1F3FD",
    html: "&#9994;&#127997;",
    category: "People & Body (hand-fingers-closed)",
    order: "",
  },
  {
    emoji: "✊🏼",
    name: "raised fist: medium-light skin tone",
    shortname: ":mediumlight_skin_tone:",
    unicode: "270A 1F3FC",
    html: "&#9994;&#127996;",
    category: "People & Body (hand-fingers-closed)",
    order: "",
  },
  {
    emoji: "✊🏻",
    name: "raised fist: light skin tone",
    shortname: ":light_skin_tone:",
    unicode: "270A 1F3FB",
    html: "&#9994;&#127995;",
    category: "People & Body (hand-fingers-closed)",
    order: "",
  },
  {
    emoji: "✊",
    name: "raised fist",
    shortname: ":fist:",
    unicode: "270a",
    html: "&#9994;",
    category: "People & Body (hand-fingers-closed)",
    order: "1188",
  },
  {
    emoji: "👇🏿",
    name: "backhand index pointing down: dark skin tone",
    shortname: ":dark_skin_tone:",
    unicode: "1F447 1F3FF",
    html: "&#128071;&#127999;",
    category: "People & Body (hand-single-finger)",
    order: "",
  },
  {
    emoji: "👇🏾",
    name: "backhand index pointing down: medium-dark skin tone",
    shortname: ":mediumdark_skin_tone:",
    unicode: "1F447 1F3FE",
    html: "&#128071;&#127998;",
    category: "People & Body (hand-single-finger)",
    order: "",
  },
  {
    emoji: "👇🏽",
    name: "backhand index pointing down: medium skin tone",
    shortname: ":medium_skin_tone:",
    unicode: "1F447 1F3FD",
    html: "&#128071;&#127997;",
    category: "People & Body (hand-single-finger)",
    order: "",
  },
  {
    emoji: "👇🏼",
    name: "backhand index pointing down: medium-light skin tone",
    shortname: ":mediumlight_skin_tone:",
    unicode: "1F447 1F3FC",
    html: "&#128071;&#127996;",
    category: "People & Body (hand-single-finger)",
    order: "",
  },
  {
    emoji: "👇🏻",
    name: "backhand index pointing down: light skin tone",
    shortname: ":light_skin_tone:",
    unicode: "1F447 1F3FB",
    html: "&#128071;&#127995;",
    category: "People & Body (hand-single-finger)",
    order: "",
  },
  {
    emoji: "👇",
    name: "backhand index pointing down",
    shortname: ":point_down:",
    unicode: "1f447",
    html: "&#128071;",
    category: "People & Body (hand-single-finger)",
    order: "1122",
  },
  {
    emoji: "🔴",
    name: "red circle",
    shortname: ":red_circle:",
    unicode: "1f534",
    html: "&#128308;",
    category: "Symbols (geometric)",
    order: "2179",
  },
  {
    emoji: "🙅🏿‍♂",
    name: "man gesturing NO: dark skin tone",
    shortname: ":dark_skin_tone:",
    unicode: "1F645 1F3FF 200D 2642",
    html: "&#128581;&#127999;&zwj;&#9794;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙅🏾‍♂",
    name: "man gesturing NO: medium-dark skin tone",
    shortname: ":mediumdark_skin_tone:",
    unicode: "1F645 1F3FE 200D 2642",
    html: "&#128581;&#127998;&zwj;&#9794;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙅🏽‍♂",
    name: "man gesturing NO: medium skin tone",
    shortname: ":medium_skin_tone:",
    unicode: "1F645 1F3FD 200D 2642",
    html: "&#128581;&#127997;&zwj;&#9794;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙅🏼‍♂",
    name: "man gesturing NO: medium-light skin tone",
    shortname: ":mediumlight_skin_tone:",
    unicode: "1F645 1F3FC 200D 2642",
    html: "&#128581;&#127996;&zwj;&#9794;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙅🏻‍♂",
    name: "man gesturing NO: light skin tone",
    shortname: ":light_skin_tone:",
    unicode: "1F645 1F3FB 200D 2642",
    html: "&#128581;&#127995;&zwj;&#9794;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙅‍♂",
    name: "man gesturing NO",
    shortname: ":man_gesturing_NO:",
    unicode: "1F645 200D 2642",
    html: "&#128581;&zwj;&#9794;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙅🏿",
    name: "person gesturing NO: dark skin tone",
    shortname: ":dark_skin_tone:",
    unicode: "1F645 1F3FF",
    html: "&#128581;&#127999;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙅🏾",
    name: "person gesturing NO: medium-dark skin tone",
    shortname: ":mediumdark_skin_tone:",
    unicode: "1F645 1F3FE",
    html: "&#128581;&#127998;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙅🏽",
    name: "person gesturing NO: medium skin tone",
    shortname: ":medium_skin_tone:",
    unicode: "1F645 1F3FD",
    html: "&#128581;&#127997;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙅🏼",
    name: "person gesturing NO: medium-light skin tone",
    shortname: ":mediumlight_skin_tone:",
    unicode: "1F645 1F3FC",
    html: "&#128581;&#127996;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙅🏻",
    name: "person gesturing NO: light skin tone",
    shortname: ":light_skin_tone:",
    unicode: "1F645 1F3FB",
    html: "&#128581;&#127995;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙅",
    name: "person gesturing NO",
    shortname: ":no_good:",
    unicode: "1f645",
    html: "&#128581;",
    category: "People & Body (person-gesture)",
    order: "531",
  },
  {
    emoji: "💥",
    name: "collision",
    shortname: ":boom:",
    unicode: "1f4a5",
    html: "&#128165;",
    category: "Smileys & Emotion (emotion)",
    order: "1305",
  },
  {
    emoji: "💭",
    name: "thought balloon",
    shortname: ":thought_balloon:",
    unicode: "1f4ad",
    html: "&#128173;",
    category: "Smileys & Emotion (emotion)",
    order: "1312",
  },
  {
    emoji: "👅",
    name: "tongue",
    shortname: ":tongue:",
    unicode: "1f445",
    html: "&#128069;",
    category: "People & Body (body-parts)",
    order: "1282",
  },
  {
    emoji: "💩",
    name: "pile of poo",
    shortname: ":poop:",
    unicode: "1f4a9",
    html: "&#128169;",
    category: "Smileys & Emotion (face-costume)",
    order: "85",
  },
  {
    emoji: "😰",
    name: "anxious face with sweat",
    shortname: ":cold_sweat:",
    unicode: "1f630",
    html: "&#128560;",
    category: "Smileys & Emotion (face-concerned)",
    order: "61",
  },
  {
    emoji: "💎",
    name: "gem stone",
    shortname: ":gem:",
    unicode: "1f48e",
    html: "&#128142;",
    category: "Objects (clothing)",
    order: "1341",
  },
  {
    emoji: "🙆🏿‍♂",
    name: "man gesturing OK: dark skin tone",
    shortname: ":dark_skin_tone:",
    unicode: "1F646 1F3FF 200D 2642",
    html: "&#128582;&#127999;&zwj;&#9794;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙆🏾‍♂",
    name: "man gesturing OK: medium-dark skin tone",
    shortname: ":mediumdark_skin_tone:",
    unicode: "1F646 1F3FE 200D 2642",
    html: "&#128582;&#127998;&zwj;&#9794;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙆🏽‍♂",
    name: "man gesturing OK: medium skin tone",
    shortname: ":medium_skin_tone:",
    unicode: "1F646 1F3FD 200D 2642",
    html: "&#128582;&#127997;&zwj;&#9794;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙆🏼‍♂",
    name: "man gesturing OK: medium-light skin tone",
    shortname: ":mediumlight_skin_tone:",
    unicode: "1F646 1F3FC 200D 2642",
    html: "&#128582;&#127996;&zwj;&#9794;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙆🏻‍♂",
    name: "man gesturing OK: light skin tone",
    shortname: ":light_skin_tone:",
    unicode: "1F646 1F3FB 200D 2642",
    html: "&#128582;&#127995;&zwj;&#9794;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙆‍♂",
    name: "man gesturing OK",
    shortname: ":man_gesturing_OK:",
    unicode: "1F646 200D 2642",
    html: "&#128582;&zwj;&#9794;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙆🏿",
    name: "person gesturing OK: dark skin tone",
    shortname: ":dark_skin_tone:",
    unicode: "1F646 1F3FF",
    html: "&#128582;&#127999;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙆🏾",
    name: "person gesturing OK: medium-dark skin tone",
    shortname: ":mediumdark_skin_tone:",
    unicode: "1F646 1F3FE",
    html: "&#128582;&#127998;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙆🏽",
    name: "person gesturing OK: medium skin tone",
    shortname: ":medium_skin_tone:",
    unicode: "1F646 1F3FD",
    html: "&#128582;&#127997;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙆🏼",
    name: "person gesturing OK: medium-light skin tone",
    shortname: ":mediumlight_skin_tone:",
    unicode: "1F646 1F3FC",
    html: "&#128582;&#127996;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙆🏻",
    name: "person gesturing OK: light skin tone",
    shortname: ":light_skin_tone:",
    unicode: "1F646 1F3FB",
    html: "&#128582;&#127995;",
    category: "People & Body (person-gesture)",
    order: "",
  },
  {
    emoji: "🙆",
    name: "person gesturing OK",
    shortname: ":ok_woman:",
    unicode: "1f646",
    html: "&#128582;",
    category: "People & Body (person-gesture)",
    order: "549",
  },
  {
    emoji: "🍕",
    name: "pizza",
    shortname: ":pizza:",
    unicode: "1f355",
    html: "&#127829;",
    category: "Food & Drink (food-prepared)",
    order: "1484",
  },
  {
    emoji: "😹",
    name: "cat with tears of joy",
    shortname: ":joy_cat:",
    unicode: "1f639",
    html: "&#128569;",
    category: "Smileys & Emotion (cat-face)",
    order: "89",
  },
  {
    emoji: "🌞",
    name: "sun with face",
    shortname: ":sun_with_face:",
    unicode: "1f31e",
    html: "&#127774;",
    category: "Travel & Places (sky & weather)",
    order: "1726",
  },
  {
    emoji: "🍃",
    name: "leaf fluttering in wind",
    shortname: ":leaves:",
    unicode: "1f343",
    html: "&#127811;",
    category: "Animals & Nature (plant-other)",
    order: "1448",
  },
  {
    emoji: "💦",
    name: "sweat droplets",
    shortname: ":sweat_drops:",
    unicode: "1f4a6",
    html: "&#128166;",
    category: "Smileys & Emotion (emotion)",
    order: "1306",
  },
  {
    emoji: "🐧",
    name: "penguin",
    shortname: ":penguin:",
    unicode: "1f427",
    html: "&#128039;",
    category: "Animals & Nature (animal-bird)",
    order: "1394",
  },
  {
    emoji: "💤",
    name: "zzz",
    shortname: ":zzz:",
    unicode: "1f4a4",
    html: "&#128164;",
    category: "Smileys & Emotion (emotion)",
    order: "1302",
  },
  {
    emoji: "🚶🏿‍♀",
    name: "woman walking: dark skin tone",
    shortname: ":dark_skin_tone:",
    unicode: "1F6B6 1F3FF 200D 2640",
    html: "&#128694;&#127999;&zwj;&#9792;",
    category: "People & Body (person-activity)",
    order: "",
  },
  {
    emoji: "🚶🏾‍♀",
    name: "woman walking: medium-dark skin tone",
    shortname: ":mediumdark_skin_tone:",
    unicode: "1F6B6 1F3FE 200D 2640",
    html: "&#128694;&#127998;&zwj;&#9792;",
    category: "People & Body (person-activity)",
    order: "",
  },
  {
    emoji: "🚶🏽‍♀",
    name: "woman walking: medium skin tone",
    shortname: ":medium_skin_tone:",
    unicode: "1F6B6 1F3FD 200D 2640",
    html: "&#128694;&#127997;&zwj;&#9792;",
    category: "People & Body (person-activity)",
    order: "",
  },
  {
    emoji: "🚶🏼‍♀",
    name: "woman walking: medium-light skin tone",
    shortname: ":mediumlight_skin_tone:",
    unicode: "1F6B6 1F3FC 200D 2640",
    html: "&#128694;&#127996;&zwj;&#9792;",
    category: "People & Body (person-activity)",
    order: "",
  },
  {
    emoji: "🚶🏻‍♀",
    name: "woman walking: light skin tone",
    shortname: ":light_skin_tone:",
    unicode: "1F6B6 1F3FB 200D 2640",
    html: "&#128694;&#127995;&zwj;&#9792;",
    category: "People & Body (person-activity)",
    order: "",
  },
  {
    emoji: "🚶‍♀",
    name: "woman walking",
    shortname: ":woman_walking:",
    unicode: "1F6B6 200D 2640",
    html: "&#128694;&zwj;&#9792;",
    category: "People & Body (person-activity)",
    order: "",
  },
  {
    emoji: "🚶🏿",
    name: "person walking: dark skin tone",
    shortname: ":dark_skin_tone:",
    unicode: "1F6B6 1F3FF",
    html: "&#128694;&#127999;",
    category: "People & Body (person-activity)",
    order: "",
  },
  {
    emoji: "🚶🏾",
    name: "person walking: medium-dark skin tone",
    shortname: ":mediumdark_skin_tone:",
    unicode: "1F6B6 1F3FE",
    html: "&#128694;&#127998;",
    category: "People & Body (person-activity)",
    order: "",
  },
  {
    emoji: "🚶🏽",
    name: "person walking: medium skin tone",
    shortname: ":medium_skin_tone:",
    unicode: "1F6B6 1F3FD",
    html: "&#128694;&#127997;",
    category: "People & Body (person-activity)",
    order: "",
  },
  {
    emoji: "🚶🏼",
    name: "person walking: medium-light skin tone",
    shortname: ":mediumlight_skin_tone:",
    unicode: "1F6B6 1F3FC",
    html: "&#128694;&#127996;",
    category: "People & Body (person-activity)",
    order: "",
  },
  {
    emoji: "🚶🏻",
    name: "person walking: light skin tone",
    shortname: ":light_skin_tone:",
    unicode: "1F6B6 1F3FB",
    html: "&#128694;&#127995;",
    category: "People & Body (person-activity)",
    order: "",
  },
  {
    emoji: "🚶",
    name: "person walking",
    shortname: ":walking:",
    unicode: "1f6b6",
    html: "&#128694;",
    category: "People & Body (person-activity)",
    order: "693",
  },
  {
    emoji: "✈️",
    name: "airplane",
    shortname: ":airplane:",
    unicode: "2708",
    html: "&#9992;",
    category: "Travel & Places (transport-air)",
    order: "1650",
  },
  {
    emoji: "🎈",
    name: "balloon",
    shortname: ":balloon:",
    unicode: "1f388",
    html: "&#127880;",
    category: "Activities (event)",
    order: "1761",
  },
  {
    emoji: "⭐",
    name: "star",
    shortname: ":star:",
    unicode: "2b50",
    html: "&#11088;",
    category: "Travel & Places (sky & weather)",
    order: "1727",
  },
  {
    emoji: "🎀",
    name: "ribbon",
    shortname: ":ribbon:",
    unicode: "1f380",
    html: "&#127872;",
    category: "Activities (event)",
    order: "1770",
  },
  {
    emoji: "☑️",
    name: "check box with check",
    shortname: ":ballot_box_with_check:",
    unicode: "2611",
    html: "&#9745;",
    category: "Symbols (other-symbol)",
    order: "2079",
  },
  {
    emoji: "😟",
    name: "worried face",
    shortname: ":worried:",
    unicode: "1f61f",
    html: "&#128543;",
    category: "Smileys & Emotion (face-concerned)",
    order: "52",
  },
  {
    emoji: "🔞",
    name: "no one under eighteen",
    shortname: ":underage:",
    unicode: "1f51e",
    html: "&#128286;",
    category: "Symbols (warning)",
    order: "1999",
  },
  {
    emoji: "😨",
    name: "fearful face",
    shortname: ":fearful:",
    unicode: "1f628",
    html: "&#128552;",
    category: "Smileys & Emotion (face-concerned)",
    order: "58",
  },
]
